// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "RCS1197:Optimize StringBuilder.Append/AppendLine call.", Justification = "Allowed for readability", Scope = "module")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Not required", Scope = "module")]
[assembly: SuppressMessage("General", "RCS1118:Mark local variable as const.", Justification = "Acceptable design pattern", Scope = "module")]

[assembly: SuppressMessage("Design", "RCS1224:Make method an extension method.", Justification = "Not necessary", Scope = "member", Target = "~M:PRISMDatabaseUtils.DatabaseUtilsExtensions.GetColumnIndex(System.Collections.Generic.IReadOnlyDictionary{System.String,System.Int32},System.String)~System.Int32")]
[assembly: SuppressMessage("Design", "RCS1224:Make method an extension method.", Justification = "Not necessary", Scope = "member", Target = "~M:PRISMDatabaseUtils.DatabaseUtilsExtensions.GetColumnIndex(System.Collections.Generic.IReadOnlyDictionary{System.String,System.Int32},System.String,System.Boolean,System.Boolean)~System.Int32")]
[assembly: SuppressMessage("Redundancy", "RCS1175:Unused this parameter.", Justification = "Included so the method can resolve as an extension method", Scope = "member", Target = "~M:PRISMDatabaseUtils.DatabaseUtilsExtensions.GetLong(PRISMDatabaseUtils.IDBTools,System.Object)~System.Int64")]
[assembly: SuppressMessage("Redundancy", "RCS1175:Unused this parameter.", Justification = "Included so the method can resolve as an extension method", Scope = "member", Target = "~M:PRISMDatabaseUtils.DatabaseUtilsExtensions.GetColumnMapping(PRISMDatabaseUtils.IDBTools,System.Collections.Generic.IReadOnlyList{System.String})~System.Collections.Generic.Dictionary{System.String,System.Int32}")]
[assembly: SuppressMessage("Redundancy", "RCS1175:Unused this parameter.", Justification = "Included so the method can resolve as an extension method", Scope = "member", Target = "~M:PRISMDatabaseUtils.DatabaseUtilsExtensions.GetColumnValue(PRISMDatabaseUtils.IDBTools,System.Collections.Generic.IReadOnlyList{System.String},System.Collections.Generic.IReadOnlyDictionary{System.String,System.Int32},System.String)~System.String")]
[assembly: SuppressMessage("Redundancy", "RCS1175:Unused this parameter.", Justification = "Included so the method can resolve as an extension method", Scope = "member", Target = "~M:PRISMDatabaseUtils.DatabaseUtilsExtensions.GetColumnValue(PRISMDatabaseUtils.IDBTools,System.Collections.Generic.IReadOnlyList{System.String},System.Collections.Generic.IReadOnlyDictionary{System.String,System.Int32},System.String,System.DateTime,System.Boolean@)~System.DateTime")]
[assembly: SuppressMessage("Redundancy", "RCS1175:Unused this parameter.", Justification = "Included so the method can resolve as an extension method", Scope = "member", Target = "~M:PRISMDatabaseUtils.DatabaseUtilsExtensions.GetColumnValue(PRISMDatabaseUtils.IDBTools,System.Collections.Generic.IReadOnlyList{System.String},System.Collections.Generic.IReadOnlyDictionary{System.String,System.Int32},System.String,System.Double,System.Boolean@)~System.Double")]
[assembly: SuppressMessage("Redundancy", "RCS1175:Unused this parameter.", Justification = "Included so the method can resolve as an extension method", Scope = "member", Target = "~M:PRISMDatabaseUtils.DatabaseUtilsExtensions.GetColumnValue(PRISMDatabaseUtils.IDBTools,System.Collections.Generic.IReadOnlyList{System.String},System.Collections.Generic.IReadOnlyDictionary{System.String,System.Int32},System.String,System.Int32,System.Boolean@)~System.Int32")]
[assembly: SuppressMessage("Redundancy", "RCS1175:Unused this parameter.", Justification = "Included so the method can resolve as an extension method", Scope = "member", Target = "~M:PRISMDatabaseUtils.DatabaseUtilsExtensions.GetDouble(PRISMDatabaseUtils.IDBTools,System.Object)~System.Double")]
[assembly: SuppressMessage("Redundancy", "RCS1175:Unused this parameter.", Justification = "Included so the method can resolve as an extension method", Scope = "member", Target = "~M:PRISMDatabaseUtils.DatabaseUtilsExtensions.GetFloat(PRISMDatabaseUtils.IDBTools,System.Object)~System.Single")]
[assembly: SuppressMessage("Redundancy", "RCS1175:Unused this parameter.", Justification = "Included so the method can resolve as an extension method", Scope = "member", Target = "~M:PRISMDatabaseUtils.DatabaseUtilsExtensions.GetInteger(PRISMDatabaseUtils.IDBTools,System.Object)~System.Int32")]
[assembly: SuppressMessage("Redundancy", "RCS1175:Unused this parameter.", Justification = "Included so the method can resolve as an extension method", Scope = "member", Target = "~M:PRISMDatabaseUtils.DatabaseUtilsExtensions.GetString(PRISMDatabaseUtils.IDBTools,System.Object)~System.String")]
[assembly: SuppressMessage("Style", "IDE0034:Simplify 'default' expression", Justification = "Included for readability", Scope = "member", Target = "~M:PRISMDatabaseUtils.DatabaseUtilsExtensions.CastDBVal``1(System.Object)~``0")]
[assembly: SuppressMessage("Style", "IDE0034:Simplify 'default' expression", Justification = "Included for readability", Scope = "member", Target = "~M:PRISMDatabaseUtils.IDBTools.AddTypedParameter``1(System.Data.Common.DbCommand,System.String,PRISMDatabaseUtils.SqlType,System.Int32,``0,System.Data.ParameterDirection)~System.Data.Common.DbParameter")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Included so the method can resolve as an extension method", Scope = "member", Target = "~M:PRISMDatabaseUtils.DatabaseUtilsExtensions.GetColumnMapping(PRISMDatabaseUtils.IDBTools,System.Collections.Generic.IReadOnlyList{System.String})~System.Collections.Generic.Dictionary{System.String,System.Int32}")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Included so the method can resolve as an extension method", Scope = "member", Target = "~M:PRISMDatabaseUtils.DatabaseUtilsExtensions.GetColumnValue(PRISMDatabaseUtils.IDBTools,System.Collections.Generic.IReadOnlyList{System.String},System.Collections.Generic.IReadOnlyDictionary{System.String,System.Int32},System.String)~System.String")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Included so the method can resolve as an extension method", Scope = "member", Target = "~M:PRISMDatabaseUtils.DatabaseUtilsExtensions.GetColumnValue(PRISMDatabaseUtils.IDBTools,System.Collections.Generic.IReadOnlyList{System.String},System.Collections.Generic.IReadOnlyDictionary{System.String,System.Int32},System.String,System.DateTime,System.Boolean@)~System.DateTime")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Included so the method can resolve as an extension method", Scope = "member", Target = "~M:PRISMDatabaseUtils.DatabaseUtilsExtensions.GetColumnValue(PRISMDatabaseUtils.IDBTools,System.Collections.Generic.IReadOnlyList{System.String},System.Collections.Generic.IReadOnlyDictionary{System.String,System.Int32},System.String,System.Double,System.Boolean@)~System.Double")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Included so the method can resolve as an extension method", Scope = "member", Target = "~M:PRISMDatabaseUtils.DatabaseUtilsExtensions.GetColumnValue(PRISMDatabaseUtils.IDBTools,System.Collections.Generic.IReadOnlyList{System.String},System.Collections.Generic.IReadOnlyDictionary{System.String,System.Int32},System.String,System.Int32,System.Boolean@)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Included so the method can resolve as an extension method", Scope = "member", Target = "~M:PRISMDatabaseUtils.DatabaseUtilsExtensions.GetDouble(PRISMDatabaseUtils.IDBTools,System.Object)~System.Double")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Included so the method can resolve as an extension method", Scope = "member", Target = "~M:PRISMDatabaseUtils.DatabaseUtilsExtensions.GetFloat(PRISMDatabaseUtils.IDBTools,System.Object)~System.Single")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Included so the method can resolve as an extension method", Scope = "member", Target = "~M:PRISMDatabaseUtils.DatabaseUtilsExtensions.GetInteger(PRISMDatabaseUtils.IDBTools,System.Object)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Included so the method can resolve as an extension method", Scope = "member", Target = "~M:PRISMDatabaseUtils.DatabaseUtilsExtensions.GetLong(PRISMDatabaseUtils.IDBTools,System.Object)~System.Int64")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Included so the method can resolve as an extension method", Scope = "member", Target = "~M:PRISMDatabaseUtils.DatabaseUtilsExtensions.GetString(PRISMDatabaseUtils.IDBTools,System.Object)~System.String")]
[assembly: SuppressMessage("Redundancy", "RCS1163:Unused parameter.", Justification = "Obsolete method included for compatibility", Scope = "member", Target = "~M:PRISMDatabaseUtils.MSSQLServer.SQLServerDBTools.UpdateDatabase(System.String,System.Int32@)~System.Boolean")]
