environment:
  APPVEYOR_BLOCK_DOTNETCORE_TESTS_AUTORUN: true
version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget.exe restore PRISM.sln
build:
  project: PRISM.sln
  verbosity: minimal
test:
  categories:
    except:
    - DatabaseIntegrated
    - SkipNetworkService
    - DatabaseNamedUser
    - PNL_Domain
artifacts:
- path: bin\Release\net462\PRISM.dll
- path: PRISMWin\bin\Release\net462\PRISMWin.dll
- path: bin\Release\PRISM-Library*.nupkg
- path: PRISMWin\bin\Release\PRISMWin-Library*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: K/JOcKhtKsDzJTZm384EnU3rqil/gUr7BqLfdQiZiRLDA76hMtgNAQ8//ZAku3sd
  skip_symbols: true
