environment:
  APPVEYOR_BLOCK_DOTNETCORE_TESTS_AUTORUN: true
version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget.exe restore PRISM.sln
build:
  project: PRISM.sln
  verbosity: minimal
test:
  categories:
    except:
    - DatabaseIntegrated
    - DatabaseNamedUser
    - DesktopInteraction
    - PNL_Domain
artifacts:
- path: PRISM\bin\Release\net462\PRISM.dll
- path: PRISMDatabaseUtils\bin\Release\net462\PRISMDatabaseUtils.dll
- path: PRISMWin\bin\Release\net462\PRISMWin.dll
- path: PRISM\bin\Release\PRISM-Library*.nupkg
- path: PRISMDatabaseUtils\bin\Release\PRISM-DatabaseUtils*.nupkg
- path: PRISMWin\bin\Release\PRISMWin-Library*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: n9oXSkH88J7JrYQelJg/lIvcl1nIzRdPL3yAG3z3SJGSz6P8t9C1ehKXjiRsilLl
  skip_symbols: true
